version: 2
services:
  bookshelf:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env:
      FORGO_DIR: ${FORGO_DIR}
      FORGO_DR_IMPSE: dengush  
    ports:
      - "5000:5000"  

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  