name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  BACKEND_IMAGE: devops-project-backend
  FRONTEND_IMAGE: devops-project-frontend
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
        buildkitd-config-inline: |
          [worker.oci]
            max-parallelism = 4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ env.GITHUB_SHA }}
        build-args: |
          NODE_ENV=production
        provenance: true
        sbom: true

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        file: ./Frontend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ env.GITHUB_SHA }}
        build-args: |
          NODE_ENV=production
        provenance: true
        sbom: true
