name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/devops-project-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/devops-project-backend:${{ github.sha }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/devops-project-frontend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/devops-project-frontend:${{ github.sha }}

      - name: Install Docker Compose
        if: ${{ contains(github.event.head_commit.message, 'compose') || contains(github.event.pull_request.title, 'compose') }}
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname  -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run docker-compose down
        if: ${{ always() && steps.install-docker-compose.outcome == 'success' }}
        id: compose-down
        run: |
          docker-compose down || echo "No running containers or docker-compose.yaml not found"
